### ISSUE TITLE
重装程序问题

### ISSUE THREAD

**Issue by wlqb2001** [spiritLHLS/traffmonetizer-one-click-command-installation#5]
./tm.sh: line 61: 534867 Killed                  docker run -d --name $NAME traffmonetizer/cli:$ARCH start accept --token "$TMTOKEN" > /dev/null 2>&1

卸载程序后重装提示这个怎么解决。。。

**Comment by spiritLHLS** [comment]
docker ps -a 
找到 traffmonetizer 对应的第一列的那一行
然后 
docker stop 那串东西
docker rm 那串东西
之后你的docker应该就正常了

**Comment by spiritLHLS** [comment]
![图片](https://user-images.githubusercontent.com/103393591/198816428-e51aa581-eaff-4e9c-84fd-f9afa7a4fc11.png)
6ceae32b23b9 这就是那串东西

**Comment by fscarmen** [comment]
会这样吗？能复现？实在不行我再处理一下

https://github.com/fscarmen/traffmonetizer
