### ISSUE TITLE
多个IP 挂机的问题

### ISSUE THREAD

**Issue by wlqb2001** [spiritLHLS/traffmonetizer-one-click-command-installation#7]
甲骨文最多可以开4台实例，每个实例可附加3个IP，合计12个IP，相当于12台vps。官网有教程https://hub.docker.com/r/traffmonetizer/cli
大佬能不能给介绍下呢，小白求助

**Comment by spiritLHLS** [comment]
这方面没搞过，有空再看看

**Comment by wlqb2001** [comment]
> 
好的，大佬有空看看吧，这个项目多挂点ip还是可以赚钱的...

**Comment by spiritLHLS** [comment]
目前看来没啥赚头，不准备开发本功能
